apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.name }}-pv-claim
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.mysql.port }}
  clusterIP: None
  selector:
    app: {{ .Values.mysql.nameApp }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.mysql.serviceName | quote }}
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.nameApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.nameApp }}
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        ports:
        - containerPort: {{ .Values.mysql.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.secret.root_pswd | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.secret.db | quote }}
        - name: MYSQL_USER
          value: {{ .Values.secret.user | quote }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.secret.pswd | quote }}
        volumeMounts:
        - name: {{ .Values.mysql.name }}-ps
          mountPath: /var/lib/mysql
      volumes:
      - name: {{ .Values.mysql.name }}-ps
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.name }}-pv-claim
