apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-from-wordpress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.mysql.nameApp }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.wordpress.nameApp }}