apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.wordpress.name }}-pv-claim
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.wordpress.port }}
      targetPort: {{ .Values.wordpress.targetPort }}
      nodePort: {{ .Values.wordpress.nodePort }}
  selector:
    app: {{ .Values.wordpress.nameApp }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wordpress.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.wordpress.nameApp }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.wordpress.nameApp }}
    spec:
      containers:
      - name: {{ .Values.wordpress.name }}
        image: {{ .Values.wordpress.image }}
        ports:
        - containerPort: {{ .Values.wordpress.targetPort }}
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
        env:
        - name: WORDPRESS_DB_HOST
          value: "{{ .Values.mysql.nameApp }}:{{ .Values.mysql.port }}"
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.secret.db | quote }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.secret.user | quote }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.secret.pswd | quote }}
        volumeMounts:
        - name: {{ .Values.wordpress.name }}-ps
          mountPath: /var/www/html
      volumes:
      - name: {{ .Values.wordpress.name }}-ps
        persistentVolumeClaim:
          claimName: {{ .Values.wordpress.name }}-pv-claim
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.wordpress.name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.wordpress.name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpuUtilization }}