version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.2
    expose:
      - 9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  fluentd:
    container_name: fluentd
    image: ghcr.io/codeby-devops/fluentd:logging
    ports:
      - 24224:24224
    volumes:
      - ./conf/fluent.conf:/fluentd/etc/fluent.conf

  kibana:
    container_name: kibana
    image: kibana:7.6.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
