version: "3.3"
services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/opt/bitnami/prometheus/data
      - "./conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml"
      - "./conf/django.rules:/opt/bitnami/prometheus/conf/django.rules"

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
    ports:
      - 3000:3000

volumes:
  prometheus_data:
  grafana_data:
