pipeline {
    agent {
        docker {
            image 'maven:3.9.9'
            args '-v /root/.m2:/root/.m2'
        }
    }
    
    environment {
        GITHUB_URL = "https://github.com/aldromanov/codeby-devops.git"
        GITHUB_CRED = "github"
        GITHUB_BRANCH = "lesson26"
        APP_DIR = "lesson26/world"
    }
    
    stages {
        stage('CheckOut') {
            steps {
                git branch: env.GITHUB_BRANCH, changelog: false, poll: false, credentialsId: env.GITHUB_CRED , url: env.GITHUB_URL
            }
        }
        stage('Build') {
            steps {
                dir(env.APP_DIR) {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir(env.APP_DIR) {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './${env.APP_DIR}/jenkins/scripts/deliver.sh'
            }
        }
    }
}