pipeline {
    agent {
        docker {
            image 'maven:3.9.9'
            args '-v /root/.m2:/root/.m2'
        }
    }
    
    environment {
        APP_DIR = "lesson26/world"
    }

    stages {
        stage('Build') {
            steps {
                dir(env.APP_DIR) {
                    sh 'mvn -B -DskipTests clean package'
                }
                
            }
        }
        stage('Test') {
            steps {
                dir(env.APP_DIR) {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit '${env.APP_DIR}/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                dir(env.APP_DIR) {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
