apiVersion: v1
kind: ServiceAccount
metadata:
  name: diagnostic-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reader-pods
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-reader-pods
  namespace: dev
subjects:
- kind: ServiceAccount
  name: diagnostic-sa
  namespace: dev
roleRef:
  kind: Role
  name: reader-pods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: diagnostic
  namespace: dev
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: diagnostic-sa
          containers:
          - name: diagnostic
            image: bitnami/kubectl
            command: ["sh", "-c", "echo 'WordPress Pods:' && kubectl get pods -n dev -l app=wordpress"]
          restartPolicy: Never