ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant"
  
  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.201"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "server"
	    vb.gui = false
      vb.memory = "512"
    end
    server.vm.provision "shell", path: "provision_server.sh"
  end
  
  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.202"
    client.vm.provider "virtualbox" do |vb|
      vb.name = "client"
	    vb.gui = false
      vb.memory = "512"
    end
    client.vm.provision "shell", path: "provision_client.sh"
  end
end
