---
- name: Install Apache Ubuntu
  apt:
    name: apache2
    state: present
  become: yes

- name: Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: true
  become: yes
