ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", path: "scripts/copy_key.sh"
  config.vm.provision "shell", path: "scripts/install_key.sh"
  
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "private_network", ip: "192.168.56.201"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu"
    end
  end
  
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos"
    centos.vm.network "private_network", ip: "192.168.56.202"
    centos.vm.provider "virtualbox" do |vb|
      vb.name = "centos"
    end
    centos.vm.provision "shell", path: "scripts/copy_yum.sh"
    centos.vm.provision "shell", path: "scripts/update_yum.sh"
  end
end
