pipeline {
    agent {
        docker {
            image 'maven:3.9.9'
            args '-v /root/.m2:/root/.m2'
        }
    }
    
    environment {
        GITHUB_URL = "https://github.com/aldromanov/codeby-devops.git"
        GITHUB_CRED = "github"
        GITHUB_BRANCH = "lesson26"
        APP_DEVOPS = "lesson26/devops"
        APP_JENKINS = "lesson26/jenkins"
        APP_WORLD = "lesson26/world"
    }
    
    stages {
        stage('CheckOut') {
            steps {
                git branch: env.GITHUB_BRANCH, changelog: false, poll: false, credentialsId: env.GITHUB_CRED , url: env.GITHUB_URL
            }
        }
        stage('Build and Test APP') {
            parallel{
                stage('APP DEVOPS') {
                    steps {
                        stage('Build') {
                            steps {
                                dir(env.APP_DEVOPS) {
                                    sh 'mvn -B -DskipTests clean package'
                                }
                            }
                        }
                        stage('Test') {
                            steps {
                                dir(env.APP_DEVOPS) {
                                    sh 'mvn test'
                                }
                            }
                            post {
                                always {
                                    junit '**/target/surefire-reports/*.xml'
                                }
                            }
                        }
                    }
                    
                }
                stage('APP JENKINS') {
                     steps {
                        stage('Build') {
                            steps {
                                dir(env.APP_JENKINS) {
                                    sh 'mvn -B -DskipTests clean package'
                                }
                            }
                        }
                        stage('Test') {
                            steps {
                                dir(env.APP_JENKINS) {
                                    sh 'mvn test'
                                }
                            }
                            post {
                                always {
                                    junit '**/target/surefire-reports/*.xml'
                                }
                            }
                        }
                    }
                }
                stage('APP WORLD') {
                    steps {
                        stage('Build') {
                            steps {
                                dir(env.APP_WORLD) {
                                    sh 'mvn -B -DskipTests clean package'
                                }
                            }
                        }
                        stage('Test') {
                            steps {
                                dir(env.APP_WORLD) {
                                    sh 'mvn test'
                                }
                            }
                            post {
                                always {
                                    junit '**/target/surefire-reports/*.xml'
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

