pipeline {
    agent {
        docker {
            image 'maven:3.9.9'
            args '-v /root/.m2:/root/.m2'
        }
    }
    
    environment {
        GITHUB_URL = "https://github.com/aldromanov/codeby-devops.git"
        GITHUB_CRED = "github"
        GITHUB_BRANCH = "lesson26"
        APP_DEVOPS = "lesson26/devops"
        APP_JENKINS = "lesson26/jenkins"
        APP_WORLD = "lesson26/world"
    }
    
    stages {
        stage('Check out') {
            steps {
                git branch: env.GITHUB_BRANCH, changelog: false, credentialsId: env.GITHUB_CRED, poll: false, url: env.GITHUB_URL
            }
        }
        stage('Build and Test APP') {
            parallel {
                stage('DEVOPS') {
                    when { changeset "${env.APP_DEVOPS}/**/*.java" }
                    stages {
                        stage ('Build DEVOPS') {
                            steps {
                                dir(env.APP_DEVOPS) {
                                    sh 'mvn -B -DskipTests clean package'
                                }
                            }
                        }       
                        stage ('Test DEVOPS') {
                            steps {
                                dir(env.APP_DEVOPS) {
                                    sh 'mvn test'
                                }
                            }
                            post {
                                always {
                                    junit '**/target/surefire-reports/*.xml'
                                    archiveArtifacts '**/target/*.jar'
                                }
                            }
                        }       
                    }
                }
                stage('JENKINS') {
                    when { changeset "${env.APP_JENKINS}/**/*.java" }
                    stages {
                        stage ('Build JENKINS') {
                            steps {
                                dir(env.APP_JENKINS) {
                                    sh 'mvn -B -DskipTests clean package'
                                }
                            }
                        }       
                        stage ('Test JENKINS') {
                            steps {
                                dir(env.APP_JENKINS) {
                                    sh 'mvn test'
                                }
                            }
                            post {
                                always {
                                    junit '**/target/surefire-reports/*.xml'
                                    archiveArtifacts '**/target/*.jar'
                                }
                            }
                        }       
                    }
                }
                stage('WORLD') {
                    when { changeset "${env.APP_WORLD}/**/*.java" }
                    stages {
                        stage ('Build WORLD') {
                            steps {
                                dir(env.APP_WORLD) {
                                    sh 'mvn -B -DskipTests clean package'
                                }
                            }
                        }       
                        stage ('Test WORLD') {
                            steps {
                                dir(env.APP_WORLD) {
                                    sh 'mvn test'
                                }
                            }
                            post {
                                always {
                                    junit '**/target/surefire-reports/*.xml'
                                    archiveArtifacts '**/target/*.jar'
                                }
                            }
                        }       
                    }
                }
            }   
        }
    }
}    
