version: '3.3'
services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    - prometheus_data:/opt/bitnami/prometheus/data
    - './prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml'
    networks:
      - monitoring

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - '9100:9100'
    networks:
      - monitoring

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    privileged: true
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    ports:
      - '8080:8080'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - monitoring
  
  alertmanager:
    image: bitnami/alertmanager:latest
    volumes:
      - ./alertmanager.yml:/opt/bitnami/alertmanager/conf/config.yml
    ports:
    - 9093:9093
    networks:
      - monitoring

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    volumes:
      - ./blackbox.yaml:/config/blackbox.yaml
    command:
      - '--config.file=/config/blackbox.yaml'
    restart: unless-stopped
    ports:
      - 9115:9115
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring: